name: 🚀 Deploy to Staging (Scaleway)

on:
  push:
    branches:
      - trunk

jobs:
  deploy:
    name: Deploy to dev.astrobear.fr
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🔐 Set up SSH agent
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 📝 Generate .env file on server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_HOST }} << 'EOF'
          cat <<EOT > /root/astrobear/.env
          FRONTEND_BASE_URL=${{ vars.FRONTEND_BASE_URL }}
          BACKEND_BASE_URL=${{ vars.BACKEND_BASE_URL }}

          ADMIN_PASSWORD=${{ secrets.DIRECTUS_ADMIN_PASSWORD }}

          DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }}
          DISCORD_CLIENT_SECRET=${{ secrets.DISCORD_CLIENT_SECRET }}
          DISCORD_REDIRECT_URI=${{ secrets.DISCORD_REDIRECT_URI }}
          EOT
          EOF

      - name: 📝 Generate .env file on frontend server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_HOST }} << 'EOF'
          cat <<EOT > /root/astrobear/frontend/.env
          VITE_FRONTEND_BASE_URL=${{ vars.FRONTEND_BASE_URL }}
          VITE_BACKEND_BASE_URL=${{ vars.BACKEND_BASE_URL }}

          VITE_WARCRAFTLOG_ID=${{ secrets.FRONTEND_BASE_URL }}
          VITE_WARCRAFTLOG_SECRET=${{ secrets.FRONTEND_BASE_URL }}

          VITE_BATTLENET_CLIENT_ID=${{ secrets.FRONTEND_BASE_URL }}
          VITE_BATTLENET_CLIENT_SECRET=${{ secrets.FRONTEND_BASE_URL }}

          VITE_DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }}
          VITE_DISCORD_CLIENT_SECRET=${{ secrets.DISCORD_CLIENT_SECRET }}
          VITE_DISCORD_REDIRECT_URI=${{ secrets.DISCORD_REDIRECT_URI }}
          EOT
          EOF

      - name: 🚀 Run deployment script
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_HOST }} "cd /home/ton_user/astrobear && ./deploy.sh"
